language: node_js
node_js:
- 11.11.0
env:
  matrix:
  - TRAVIS=true
  global:
    secure: ct+UcSBho53RItF0SGiX1MG/0nlCUl8TMayj9tLcasCbbbqklb2jm043SYnxq3+vQuqhuzScSlT0yWJaHFI214hJbFOSyujLFBp6xXDyzV5qxhS6hXp7bT52QhKOM+qB7Nl2WAQIFA1nje2HOznzVeHvbDNUE/CoWEXNRh3+5XirkXBZIoR62YENpuDt2/8BFTRFgN8QS3RPNcwSKE/eGVMIVMhKBvU14BzGYLuO5QROBQEU+3ipBn9vc+B057bwVrLfojFxOKcpzAFVYPv9zEsxQlSO4O8zUhxAZPu8R1YP0KZ7x/kdbzH+iTG2wB5mUtfjR9+a0B7ET3sLBJ/rTNcGGHlAyW//pRDLMDKyNneVV7p+NnWHRX6EDkJ012LkOj749yVyYio6HZsf9uR4HXDVtXPLg6cRxf0Gmzi28X6tWO5t9awCDZcZekOg8WvKWEexE8ULTv5uH16ubhyTr7Zz6PtzLjdNbLQX2/MEEaTIu1ndZHsKVY8ccOUisA4Zm2y9/87NsB7RAhgmyclvKuSfsLTia3CGpv5MZQXsp2m6TWGP0EXDZnkEgZNFy4AElUAYGIwoAbU7JguWhKwE5i0eyfBtd48+RDNOnmxftOMTYq2TzfdRav1niT56DnQVT/aJOjmAQNeyU5rosZpN6X9WVmyGUCGQ2clrSlwAhGM=
